container:
  image: python:latest

test_task:
  pip_cache:
    folder: ~/.cache/pip
    # fingerprint_script: cat requirements.txt
    # populate_script: pip install -r requirements.txt
    populate_script: pip install distro
  test_script:
    - pip install distro
    - python -c 'import distro, platform; print(distro.id(), repr(distro.name()), distro.version(), platform.uname())'
    - ls -al testresults/*
    - rm -f testresult/testresults*.txt
    - python test/run.py -result
    - ls -al testresults/*
    - cat testresults/testresults*.txt
