language: python

python:
  - "2.6"
  - "2.7"
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install distro
  - pip install geographiclib

script:
  - python -c 'import distro, platform; print(distro.id(), repr(distro.name()), distro.version(), platform.uname())'
  - python -c 'import geographiclib; print("geographiclib " + geographiclib.__version__)'
  - python test/run.py -result
  - ls -al testresults/*
