# <https://github.com/pypa/setuptools/blob/master/appveyor.yml>
environment:

  APPVEYOR: True
  CODECOV_ENV: APPVEYOR_JOB_NAME

  matrix:
    - APPVEYOR_JOB_NAME: "python36-x64"
      PYTHON: "C:\\Python36-x64"
    - APPVEYOR_JOB_NAME: "python27-x64"
      PYTHON: "C:\\Python27-x64"

install:
  # symlink python from a directory with a space
  - "mklink /d \"C:\\Program Files\\Python\" %PYTHON%"
  - "set PYTHON=\"C:\\Program Files\\Python\""
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "set PYTHONIOENCODING=utf-8"
  # "pip install win_unicode_console"

build: off

#cache:
#  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - "cd C:\\projects\\pygeodesy"
  - "python test\\testBases.py"
  - "python test\\run.py -results"
  - "type testresults\\testresults*Windows*.txt"

# version: '{build}'
